###############-VERSION-###################
version: '3.3'

################-SERVICIOS-################

services:
#################-ia-##########################
   ia:
    container_name: ia
    build: ./IA
    restart: always
    ports:
        - "3001:80"
    volumes: 
        - ./IA:/app
    
###################-SERVIDOR-#########################   
   servidor:
     container_name: servidor
     build: ./backend
     restart: always
     environment:
       - CHOKIDAR_USEPOLLING=true
     volumes:
       - ./backend/src:/app/src
     ports:
         - "8000:8031"
     depends_on:
         - ia


###################-CLIENTE-#########################   
   cliente:
     container_name: cliente
     build: ./app-transit
     restart: always
     ports:
         - "3000:3000"
     volumes:
        - ./app-transit/src:/app/src
     depends_on:
         - ia
         - servidor

###################-POSTGRES-#########################   

   postgres:
    container_name: postgres
    restart: always
    build: ./db
    volumes:
        - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
        - "5433:5432"


###################-REDIS_SHARPS-##########################
#   redis:
#    container_name: redis1
#    image: redis:6.2.6
#    restart: always
#    ports:
#      - "6379:6379"
#    environment:
#      - ALLOW_EMPTY_PASSWORD=yes
#    command:
#      [
#        "redis-server",
#        "--bind",
#        "redis",
#        "--maxmemory 2mb",
#        "--maxmemory-policy allkeys-lru"
#      ]
