###############-VERSION-###################
version: '3.3'

################-SERVICIOS-################

services:
#################-ia-##########################
   ia:
    container_name: ia
    build: ./IA
    restart: always
    ports:
        - "5000:80"
    volumes: 
        - ./IA:/app
    
###################-SERVIDOR-#########################   
   servidor:
     container_name: servidor
     build: ./backend
     restart: always
     environment:
       - CHOKIDAR_USEPOLLING=true
     volumes:
       - ./backend:/app
     ports:
         - "81:8031"
     depends_on:
         - ia


###################-CLIENTE-#########################   
#    cliente:
#      container_name: cliente
#      build: ./frontend
#      restart: always
#      ports:
#          - "79:80"
#      depends_on:
#          - IA
#          - servidor
